version: "3"
services:
  nginx:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./code:/var/www
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
          - php-fpm
      restart: unless-stopped

  php-fpm:
      build:
        context: ./docker/php
        dockerfile: Dockerfile
      image: custom-php:7.2-fpm
      volumes:
          - ./code:/var/www
      links:
          - mysql
      restart: unless-stopped

  mysql:
      image: mysql:5.7
      volumes:
       - /var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
       - "3306:3306"
      restart: unless-stopped

